import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import Hero from "../components/Hero.js";
import Navbar from "../components/Navbar.js";
import DisplaySection from "../components/DisplaySection.js";

import axios from "axios";

const baseURL = " http://127.0.0.1:8000/Users/";

function Home() {
  const [post, setPost] = useState({});
  useEffect(() => {
    getUsers();
  }, []);

  const getUsers = async () => {
    const { data } = await axios.get(baseURL);
    console.log(data.Response);
    setPost(data.Response[0]);
    return;
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <DisplaySection />

      <div>{post?.email}</div>
    </div>
  );
}

export default Home;
